### ISSUE TITLE
(Question) Rust Rewrite

### ISSUE THREAD

**Issue by hardBSDk** [pojntfx/multiplex#14]
Are you open to rewrite it in Rust?

**Comment by pojntfx** [comment]
Hi! Not really, mostly because the Rust WebRTC stacks aren't up to production quality yet (weron depends on this through Pion: https://github.com/pojntfx/weron) and because panrpc doesn't have a Rust version due to Rust's limited runtime reflection support: https://github.com/pojntfx/panrpc. Go is also getting better official GNOME support atm, so I see the maintenance overhead of such a change as not really worth it: https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/782
