### ISSUE TITLE
integration with qbittorrent

### ISSUE THREAD

**Issue by Martinligabue** [pojntfx/multiplex#8]
It would be nice to have it work with qbittorrent webui or something to select from previously downloaded videos, and also download them to this app instead of doing it internally.

This might solve the local file thing in https://github.com/pojntfx/multiplex/issues/3, as you could use qbittorrent to create the file and then share it.

(not sure if this helps, but qbit is also available as a flatpak).

**Comment by pojntfx** [comment]
That would be pretty cool, but I'm afraid its a bit out of scope. Maybe one of these could work:

- Registering Multiplex as a file handler. That would allow you to select a local video file, right click → "Open With", then start the playback as we currently do so that people can join the session!
- Using hTorrent (which uses https://github.com/anacrolix/torrent) to seed the file for you. This is possible - but I'd personally probably prefer using WebRTC for local files, since its fully P2P and doesn't require uploading the file to a tracker. See https://github.com/pojntfx/multiplex/issues/5 for more info ^^
